name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускать CI/CD только при push в main
  pull_request:
    branches:
      - main # Запускать при открытии PR на main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build # Деплой будет выполняться только после успешного завершения build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Добавьте ваш SSH ключ в Secrets

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@194.32.140.225 "cd /var/www/brainsoft && git pull origin main"
